audit_header: false
title: Metro Phoenix Real Estate Video Blog with Roman Kushmakov
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Roman Kushmakov
  title:
  license_number:
  about_markdown: >-
    Roman is the Founder and CEO of Roman Group with Homesmart International,
    which is the largest brokerage in state of Arizona. Over the past 12 years,
    Roman has been helping buyers and sellers in the valley their real estate
    needs. He takes pride in being go-to real estate advisor with five star
    customer service for his clients. When you contact Roman for your real
    estate needs, you can count on his market knowledge of the areas, honesty,
    and care. He will guide through the whole process with the least amount of
    stress as possible.
  market: Metro Phoenix
  brand: The Roman Group | Homesmart International
  brokerage:
  address: '8388 E Hartford Dr #100 Scottsdale AZ 85255'
  phone: 480-442-5179
  phone_type:
  phone2:
  phone2_type:
  email: Roman@HomeSeekersGroup.com
  url: 'http://www.FreeValleyHomeSearch.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.freevalleyhomesearch.com/selling/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.freevalleyhomesearch.com/search/advanced_search/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'http://www.freevalleyhomesearch.com/selling/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'http://www.freevalleyhomesearch.com/search/advanced_search/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/The-Roman-Group-Homesmart-Realty-562167483905719/'
  linkedin_url: 'https://www.linkedin.com/in/roman-kushmakov-803b5713/'
  gplus_url: 'https://plus.google.com/b/115182437513395187339/115182437513395187339'
  youtube_url: 'https://www.youtube.com/channel/UCQDN6XX5eMmw96lolIPYnsQ'
  twitter_url: 'https://twitter.com/Roman_HSG'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Roman-Kushmakov/'
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#803434'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'